apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: smells.kubepattern.dev
spec:
  group: kubepattern.dev
  names:
    plural: smells
    singular: smell
    kind: Smell
    shortNames:
      - smell
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Severity
          type: string
          description: "Smell severity (LOW, MEDIUM, HIGH, CRITICAL)"
          jsonPath: .spec.severity
        - name: Target Kind
          type: string
          description: "Kind of the target resource"
          jsonPath: .spec.target.kind
        - name: Target Name
          type: string
          description: "Name of the target resource"
          jsonPath: .spec.target.name
        - name: Target Namespace
          type: string
          description: "Namespace of the target resource"
          jsonPath: .spec.target.namespace
          priority: 1
        - name: Message
          type: string
          description: "Smell message"
          jsonPath: .spec.message
          priority: 1
        - name: Suppressed
          type: boolean
          description: "Indicates if the smell is ignored"
          jsonPath: .spec.suppress
          priority: 1
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - name
                - category
              properties:
                name:
                  type: string
                  description: "Smell name"
                category:
                  type: string
                  description: "Smell category"
                reference:
                  type: string
                  description: "Smell Docs"
                pattern:
                  type: object
                  properties:
                    name:
                      type: string
                    version:
                      type: string
                message:
                  type: string
                severity:
                  type: string
                  enum:
                    - LOW
                    - MEDIUM
                    - HIGH
                    - CRITICAL
                suppress:
                  type: boolean
                  description: "Resource to suppress (false positives)"
                  default: false
                target:
                  type: object
                  required:
                    - apiVersion
                    - kind
                    - uid
                    - name
                  properties:
                    apiVersion:
                      type: string
                    kind:
                      type: string
                    name:
                      type: string
                    namespace:
                      type: string
                    uid:
                      type: string