# Target image for the Go-based KubePattern analyzer
image:
  repository: ghcr.io/kubepattern/kubepattern
  pullPolicy: IfNotPresent
  tag: 0.0.4
# CronJob scheduling configuration
schedule: "0 * * * *" # Runs every hour by default
suspend: false        # Set to true to temporarily suspend the CronJob

resources:
  requests:
    memory: "256Mi"
    cpu: "200m"
  limits:
    memory: "1Gi"
    cpu: "1000m"


tolerations: {}
nodeSelector: {}
affinity: {}

RBAC:
  # Define the RBAC rules for KubePattern (to scan only specific resources, modify accordingly)
  rules:
    - apiGroups: ["*"]
      resources: ["*"]
      verbs: ["get", "list", "watch"]

analysis:
  # Save the smells in the namespace of the involved resources
  saveInNamespace: false
  # Default output namespace if saveInNamespace == false or for cluster-scoped resources
  targetNamespace: kubepattern-analysis-ns

# Deploy example resources to test KubePattern (a Pattern CRD and a matching Pod)
example:
  enabled: true
