# Informer-cached list of every pages.widgets.templates.krateo.io (v1beta1), all namespaces.
apiVersion: kyverno.io/v2
kind: GlobalContextEntry
metadata:
  name: pages.widgets.templates.krateo.io
spec:
  kubernetesResource:
    group: widgets.templates.krateo.io
    version: v1beta1
    resource: pages
