# Informer-cached list of every panels.widgets.templates.krateo.io (v1beta1), all namespaces.
apiVersion: kyverno.io/v2
kind: GlobalContextEntry
metadata:
  name: panels.widgets.templates.krateo.io
spec:
  kubernetesResource:
    group: widgets.templates.krateo.io
    version: v1beta1
    resource: panels
