# Informer-cached list of every serviceaccounts (v1), all namespaces.
apiVersion: kyverno.io/v2
kind: GlobalContextEntry
metadata:
  name: serviceaccounts.core
spec:
  kubernetesResource:
    group: ""
    version: v1
    resource: serviceaccounts
