---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kubepattern-dev-v1-pattern
  failurePolicy: Fail
  name: vpattern-v1.kb.io
  rules:
  - apiGroups:
    - kubepattern.dev
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - patterns
  sideEffects: None
