apiVersion: kubepattern.dev/v1
kind: Pattern
metadata:
  name: rule-e5
spec:
  displayName: Rule E5
  category: General
  severity: MEDIUM
  message: "Finding on {{target.metadata.name}}"
  target:
    kind: Function
    apiVersion: pkg.crossplane.io/v1
    plural: functions
  dependencies:
    - id: composition
      kind: Composition
      apiVersion: apiextensions.crossplane.io/v1
      plural: compositions
    - id: operation
      kind: Operation
      apiVersion: ops.crossplane.io/v1alpha1
      plural: operations
    - id: cronoperation
      kind: CronOperation
      apiVersion: ops.crossplane.io/v1alpha1
      plural: cronoperations
    - id: watchoperation
      kind: WatchOperation
      apiVersion: ops.crossplane.io/v1alpha1
      plural: watchoperations
  relationships:
    matchNone:
      - with: composition
        type: custom
        criteria:
          - targetPath: "metadata.name"
            dependencyPath: "spec.pipeline[*].functionRef.name"
            operator: EQUALS
      - with: operation
        type: custom
        criteria:
          - targetPath: "metadata.name"
            dependencyPath: "spec.pipeline[*].functionRef.name"
            operator: EQUALS
      - with: cronoperation
        type: custom
        criteria:
          - targetPath: "metadata.name"
            dependencyPath: "spec.operationTemplate.spec.pipeline[*].functionRef.name"
            operator: EQUALS
      - with: watchoperation
        type: custom
        criteria:
          - targetPath: "metadata.name"
            dependencyPath: "spec.operationTemplate.spec.pipeline[*].functionRef.name"
            operator: EQUALS
