apiVersion: kubepattern.dev/v1
kind: Pattern
metadata:
  labels:
    app.kubernetes.io/name: kubepattern-go
    app.kubernetes.io/managed-by: kustomize
  name: pattern-sample
spec:
  displayName: No Patterns applied
  category: KubePattern
  severity: LOW
  message: "No Patterns applied!"
  reference: "https://kubepattern.dev/docs/core/patterns"
  target:
    kind: Pattern
    apiVersion: kubepattern.dev/v1
    plural: patterns
    filters:
      matchNone:
        - path: "metadata.name"
          operator: EQUALS
          values:
            - "pattern-sample"
      matchAny:
        - path: "kind"
          operator: EXISTS
