apiVersion: kubepattern.dev/v1
kind: Smell
metadata:
  labels:
    app.kubernetes.io/name: kubepattern-go
    app.kubernetes.io/managed-by: kustomize
  name: smell-sample
spec:
  name: pattern-sample
  category: KubePattern
  message: "No Patterns applied!"
  severity: LOW
  reference: "https://kubepattern.dev/docs/core/patterns"
  pattern:
    name: pattern-sample
    version: kubepattern.dev/v1
  target:
    apiVersion: kubepattern.dev/v1
    kind: Pattern
    name: pattern-sample
    uid: "00000000-0000-0000-0000-000000000000"
