apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  # The Go application can read this YAML file using libraries like Viper or Koanf
  config.yaml: |
    analysis:
      saveInNamespace: {{ .Values.analysis.saveInNamespace }}
      targetNamespace: {{ .Values.analysis.targetNamespace | quote }}
    patternRegistry:
      organizationName: {{ .Values.patternRegistry.orgName | quote }}
      repositoryBranch: {{ .Values.patternRegistry.repo.branch | quote }}
      repositoryName: {{ .Values.patternRegistry.repo.name | quote }}