{{- if .Values.example.enabled }}
# 1. Example Pattern
apiVersion: kubepattern.dev/v1
kind: Pattern
metadata:
  name: test-configmap
  labels:
    app.kubernetes.io/name: kubepattern-example
spec:
  displayName: Test ConfigMap
  category: KubePattern Tests
  severity: HIGH
  message: "ConfigMap {{ "{{" }}target.metadata.name{{ "}}" }} in namespace {{ "{{" }}target.metadata.namespace{{ "}}" }} has Pattern Test label."

  target:
    kind: ConfigMap
    apiVersion: v1
    plural: configmaps
    filters:
      matchAll:
        - path: "metadata.labels.kubepattern"
          operator: EQUALS
          values:
            - test
---
# 2. Example Pod that triggers the Pattern
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubepattern-test-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    kubepattern: test
{{- end }}