{{- if .Values.example.enabled }}
# 1. Example Pattern
apiVersion: kubepattern.dev/v1
kind: Pattern
metadata:
  name: no-pattern-applied
  labels:
    app.kubernetes.io/name: kubepattern-example
spec:
  displayName: No Patterns applied
  category: KubePattern
  severity: LOW
  message: "No Patterns applied!"
  reference: "https://kubepattern.dev/docs/core/patterns"
  target:
    kind: Pattern
    apiVersion: kubepattern.dev/v1
    plural: patterns
    filters:
      matchNone:
        - path: "metadata.name"
          operator: EQUALS
          values:
          - "no-pattern-applied"
      matchAny:
        - path: "kind"
          operator: EXISTS
          value: []
{{- end}}