apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  # Secret to access kubepattern pattern registry repository (if private)
  repository-token: {{ default "" .Values.patternRegistry.repo.token | b64enc | quote }}