name: Build Docker Image (Prod)

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine Tags
        id: vars
        run: |
          # Extract tag version removing 'v' (example: v1.0.0 --> 1.0.0)
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/v,,')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          
          # Extract short SHA (example: 1234567 --> 1234567)
          echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and Push Prod Image
        run: |
          IMAGE_ID="ghcr.io/${{ github.repository_owner }}/kubepattern"
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          
          echo "Building stable image $IMAGE_ID:$VERSION..."
          
          # Build the Docker image with the version short SHA tag
          docker build -t $IMAGE_ID:$VERSION -t $IMAGE_ID:latest -t $IMAGE_ID:sha-${{ env.SHA_SHORT }} .
          
          # Push the Docker image with the version tag, latest tag, and short SHA tag
          docker push $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:latest
          docker push $IMAGE_ID:sha-${{ env.SHA_SHORT }}