apiVersion: kyverno.io/v2
kind: GlobalContextEntry
metadata:
  name: scheduledbackups.postgresql.cnpg.io
spec:
  kubernetesResource:
    group: postgresql.cnpg.io
    version: v1
    resource: scheduledbackups
